name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 1 */2 *' # once every two months, on the first day of the month

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
