name: Release Notes

on:
  push:
    tags:
      - '*'

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.MY_TOKEN }}
