name: Tag Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semver Release Type (major,minor,patch)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Validate releaseType
        run: npx in-string-list ${{ github.event.inputs.releaseType }} major,minor,patch
      - name: Setup Git
        run: |
          git config --global user.name "Jonathan Johnson"
          git config --global user.email "jon.johnson@ucsf.edu"
      - name: Increment Version
        run: npx versionup --level ${{ github.event.inputs.releaseType }}
      - run: |
          NEW_TAG=`node -p "require('./package.json').version"`
          echo ${NEW_TAG}
          echo "new_tag=${NEW_TAG}" >> $GITHUB_ENV
      - name: Tag Version
        run: |
          git commit -a -m "${{env.new_tag}}"
          git tag v${{env.new_tag}} -m "Tagging the v${{env.new_tag}} ${{ github.event.inputs.releaseType }} release"
      - name: Push Changes
        run: git push --follow-tags
